# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release/*

variables:
  prefix: "$(Build.SourceBranchName)"
  archiveName: 'FunctionsArchive'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: 
        steps:
        - bash: |
            npm install
            npm run build --if-present
            npm prune --production
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: "$(Build.SourcesDirectory)"
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true
        # - task: PublishBuildArtifacts@1
        #   inputs:
        #     PathtoPublish: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
        #     ArtifactName: '$(archiveName)'
        #     publishLocation: 'Container'

  - stage: Deploy
    dependsOn:
      - Build
    jobs:
      - job: 
        steps:
          # - task: DownloadPipelineArtifact@2
          #   inputs:
          #     artifact: '$(archiveName)'
          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: 'sasatake-azure-service-connection'
              appType: 'functionApp'
              appName: '$(prefix)-functions'
              package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              deploymentMethod: 'zipDeploy'


        