# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release/*

variables:
  prefix: "$(Build.SourceBranchName)"

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: 
        steps:
        - bash: |
            npm install 
            npm run build --if-present
            npm prune --production
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Build.BinariesDirectory)/src/'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            ArtifactName: 'drop'
            publishLocation: 'Container'

  - stage: Deploy
    jobs:
      - job: 
        steps:
        - task: AzureFunctionApp@1
          inputs:
            azureSubscription: 'sasatake-azure-service-connection'
            appType: 'functionApp'
            appName: '$(prefix)-functions'
            package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
            deploymentMethod: 'zipDeploy'


        