# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release/*

variables:
  prefix: "$(Build.SourceBranchName)"
  archiveName: 'FunctionsArchive'
  functionName: '$(prefix)-functions'
  resourceGroupName: "$(prefix)-rg"

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: 
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '12.x'
        - task: Npm@1
          inputs:
            command: 'install'
        - task: Npm@1
          inputs:
            command: 'custom'
            customCommand: 'run build'
        - task: Npm@1
          inputs:
            command: 'custom'
            customCommand: 'run test'
        - task: Npm@1
          inputs:
            command: 'custom'
            customCommand: 'prune --production'  
        - task: CopyFiles@2
          inputs:
            SourceFolder: "$(Build.SourcesDirectory)"
            Contents: |
              host.json
              package.json
              **/node_modules/**
              **/**/function.json
              **/**/index.js
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: "$(Build.ArtifactStagingDirectory)"
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.BinariesDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Build.BinariesDirectory)/$(Build.BuildId).zip'
            ArtifactName: '$(archiveName)'

  - stage: Deploy
    dependsOn:
      - Build
    jobs:
      - job: 
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifact: '$(archiveName)'
              path: '$(Build.BinariesDirectory)/'
          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: 'sasatake-azure-service-connection'
              appType: 'functionApp'
              appName: '$(prefix)-functions'
              package: '$(Build.BinariesDirectory)/$(Build.BuildId).zip'
              deploymentMethod: 'auto'


        